### ISSUE TITLE
defaultConfig is not defined

### ISSUE THREAD

**Issue by meta-pratap-ranawat** [arabsight/aurelia-trumbowyg-plugin#1]
Hi there, 
I am getting a error on browser i.e. Unhandled rejection ReferenceError: defaultConfig is not defined.
error say that in ./node_modules/aurelia-trumbowyg-plugin/dist/**/index.js

Step followed by me
1. au new /*webpack and typescript project*/
2. npm i jquery trumbowyg aurelia-trumbowyg-plugin
3. plugin added in main.ts 
      .plugin(PLATFORM.moduleName('aurelia-trumbowyg-plugin'))
4. jquery add in wedpack.config.js
```
new ProvidePlugin({
      'jQuery': 'jquery'
    }),
```
5. au run --watch

No error node console: compiled successful
but on browser 'Hello world!' message is not visible 
on browser console shows error 
Unhandled rejection ReferenceError: defaultConfig is not defined.

Please help me to find out problem.

Thanks in advance

**Comment by arabsight** [comment]
Hi, sorry for the delay, its fixed in 0.1.5

**Comment by arabsight** [comment]
also when using webpack add the svg icons:
```js
import svgPath from 'trumbowyg/dist/ui/icons.svg';

...
aurelia.use.plugin(PLATFORM.moduleName('aurelia-trumbowyg-plugin'), {svgPath});
...
```

**Comment by meta-pratap-ranawat** [comment]
Hi @arabsight ,
Can you please let me know the webpack.config.js settings for file/url loader for SVG because when I do import svgPath from 'trumbowyg/dist/ui/icons.svg'; I get the error "Cannot find module" 'trumbowyg/dist/ui/icons.svg'

Thanks

**Comment by meta-pratap-ranawat** [comment]
Hi @arabsight ,
Sorry but I cannot find the v0.1.5 of this plugin, I can only see v0.1.2 and v0.1.1 in github

**Comment by arabsight** [comment]
the version is on npm so just reinstall, as for the svg could be a typescript thing because I use js, I didn't touch the webpack config

**Comment by meta-pratap-ranawat** [comment]
thanks @arabsight,  problem is resolved now.
