### ISSUE TITLE
cursor left jump issue

### ISSUE THREAD

**Issue by meta-pratap-ranawat** [arabsight/aurelia-trumbowyg-plugin#2]
Hi there,

**Issue One**

In version 0.1.5 
**cursor in text editor jumps to beginning position after every value typed.**
issue is due to below code in file _trumbowyg-editor.js_

```
TrumbowygEditor.prototype.valueChanged = function valueChanged(newValue) {
    (0, _jquery2.default)(this.editor).trumbowyg('html', newValue);
  };
```

In version 0.1.2
cursor is working fine in editor.

**Issue Two**

pasted value is not updated in value binding in editor

Thanks

Best Regards,
Pratap Ranawat

**Comment by arabsight** [comment]
fixed 0.1.7
